plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.0.0'
}

project.version = 'v1'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

shadowJar {
    manifest {
        attributes 'Main-Class': 'org.othello.Othello'
    }
    archiveFileName = "${'Othello'}.jar"
}

apply plugin: 'com.github.johnrengelman.shadow'